/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.joda.time.LocalTime;

public class App {
    public LocalTime getLocalTime() {
		LocalTime time = new LocalTime();
        return time;
    }

    public static void main(String[] args) {
        System.out.println("Local Time is "+ new App().getLocalTime());
    }
}
